development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: webdb
  pool: 5
  username: postgres
  password: postgres


test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: webdb
  pool: 5
  username: postgres
  password: postgres
